--  disable FK cnc_id, 放全部廠牌的AlarmCode

insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('-1','FANUC_CNC_FOCAS','no result');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('0','FANUC_CNC_FOCAS','PLEASE TURN OFF POWER');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('1','FANUC_CNC_FOCAS','TH PARITY ALARM');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('2','FANUC_CNC_FOCAS','TV PARITY ALARM');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('3','FANUC_CNC_FOCAS','TOO MANY DIGITS');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('4','FANUC_CNC_FOCAS','ADDRESS NOT FOUND');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('5','FANUC_CNC_FOCAS','NO DATA AFTER ADDRESS');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('6','FANUC_CNC_FOCAS','ILLEGAL USE OF NEGATIVE SIGN');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('7','FANUC_CNC_FOCAS','ILLEGAL USE OF DECIMAL POINT');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('9','FANUC_CNC_FOCAS','ILLEGAL ADDRESS INPUT');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('10','FANUC_CNC_FOCAS','IMPROPER G-CODE');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('11','FANUC_CNC_FOCAS','NO FEEDRATE COMMANDED');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('14','FANUC_CNC_FOCAS','CAN NOT COMMAND G95 (M series) /  ILLEGAL LEAD COMMAND (T series)');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('15','FANUC_CNC_FOCAS','TOO MANY AXES COMMANDED (M /T series)');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('20','FANUC_CNC_FOCAS','OVER TOLERANCE OF RADIUS');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('21','FANUC_CNC_FOCAS','ILLEGAL PLANE AXIS COMMANDED');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('22','FANUC_CNC_FOCAS','NO CIRCLE RADIUS');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('23','FANUC_CNC_FOCAS','ILLEGAL RADIUS COMMAND (T series)');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('25','FANUC_CNC_FOCAS','CANNOT COMMAND F0 IN G02/G03 (M series)');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('27','FANUC_CNC_FOCAS','NO AXES COMMANDED IN G43/G44 (M series)');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('28','FANUC_CNC_FOCAS','ILLEGAL PLANE SELECT');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('29','FANUC_CNC_FOCAS','ILLEGAL OFFSET VALUE (M / T series)');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('30','FANUC_CNC_FOCAS','ILLEGAL OFFSET NUMBER (M / T  series)');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('31','FANUC_CNC_FOCAS','ILLEGAL P COMMAND IN G10');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('32','FANUC_CNC_FOCAS','ILLEGAL OFFSET VALUE IN G10');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('33','FANUC_CNC_FOCAS','NO SOLUTION AT CRC (M / T series)');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('34','FANUC_CNC_FOCAS','NO CIRC ALLOWED IN ST-UP /EXT BLK (M / T series)');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('35','FANUC_CNC_FOCAS','CAN NOT COMMANDED G39 (M series) / G31 (T series)');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('36','FANUC_CNC_FOCAS','CAN NOT COMMANDED G31 (M series)');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('37','FANUC_CNC_FOCAS','CAN NOT CHANGE PLANE IN CRC (M seires) / NRC(T series)');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('38','FANUC_CNC_FOCAS','INTERFERENCE IN CIRCULAR BLOCK (M / T seires)');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('39','FANUC_CNC_FOCAS','CHF/CNR NOT ALLOWED IN NRC (T series)');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('40','FANUC_CNC_FOCAS','INTERFERENCE IN G90/G94 BLOCK (T series)');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('41','FANUC_CNC_FOCAS','INTERFERENCE IN CRC (M / T seires)');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('42','FANUC_CNC_FOCAS','G45/G48 NOT ALLOWED IN CRC (M series)');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('44','FANUC_CNC_FOCAS','G27-G30 NOT ALLOWED IN FIXED CYC (M series)');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('45','FANUC_CNC_FOCAS','ADDRESS Q NOT FOUND (G73/G83) (M series)');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('46','FANUC_CNC_FOCAS','ILLEGAL REFERENCE RETURN COMMAND');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('47','FANUC_CNC_FOCAS','ILLEGAL AXIS SELECT');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('48','FANUC_CNC_FOCAS','BASIC 3 AXIS NOT FOUND');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('49','FANUC_CNC_FOCAS','ILLEGAL OPERATION (G68/G69) (M series)');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('50','FANUC_CNC_FOCAS','CHF/CNR NOT ALLOWED IN THRD BLK (M / T series)');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('51','FANUC_CNC_FOCAS','MISSING MOVE AFTER CHF/CNR (M / T series)');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('52','FANUC_CNC_FOCAS','CODE IS NOT G01 AFTER CHF/CNR (M / T series)');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('53','FANUC_CNC_FOCAS','TOO MANY ADDRESS COMMANDS (M / T series)');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('54','FANUC_CNC_FOCAS','NO TAPER ALLOWED AFTER CHF/CNR (T series)');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('55','FANUC_CNC_FOCAS','MISSING MOVE VALUE IN CHF/CNR (M / T series)');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('56','FANUC_CNC_FOCAS','NO END POINT &amp; ANGLE IN CHF/CNR (T series)');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('57','FANUC_CNC_FOCAS','NO SOLUTION OF BLOCK END (T series)');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('58','FANUC_CNC_FOCAS','END POINT NOT FOUND (M / T series)');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('59','FANUC_CNC_FOCAS','PROGRAM NUMBER NOT FOUND');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('60','FANUC_CNC_FOCAS','SEQUENCE NUMBER NOT FOUND');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('61','FANUC_CNC_FOCAS','ADDRESS P/Q NOT FOUND IN G70-G73 (T series)');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('62','FANUC_CNC_FOCAS','ILLEGAL COMMAND IN G71-G76 (T series)');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('63','FANUC_CNC_FOCAS','SEQUENCE NUMBER NOT FOUND (T series)');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('64','FANUC_CNC_FOCAS','SHAPE PROGRAM NOT MONOTONOUSLY (T series)');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('65','FANUC_CNC_FOCAS','ILLEGAL COMMAND IN G71-G73 (T series)');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('66','FANUC_CNC_FOCAS','IMPROPER G-CODE IN G71-G73 (T series)');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('67','FANUC_CNC_FOCAS','CAN NOT ERROR IN MDI MODE (T series)');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('69','FANUC_CNC_FOCAS','FORMAT ERROR IN G70-G73 (T series)');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('70','FANUC_CNC_FOCAS','NO PROGRAM SPACE IN MEMORY');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('71','FANUC_CNC_FOCAS','DATA NOT FOUND');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('72','FANUC_CNC_FOCAS','TOO MANY PROGRAMS');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('73','FANUC_CNC_FOCAS','PROGRAM NUMBER ALREADY IN');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('74','FANUC_CNC_FOCAS','ILLEGAL PROGRAM NUMBER');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('75','FANUC_CNC_FOCAS','PROTECT');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('76','FANUC_CNC_FOCAS','ADDRESS P NOT DEFINED');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('77','FANUC_CNC_FOCAS','SUB PROGRAM NESTING ERROR');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('78','FANUC_CNC_FOCAS','NUMBER NOT FOUND');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('79','FANUC_CNC_FOCAS','PROGRAM VERIFY ERROR');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('80','FANUC_CNC_FOCAS','G37 ARRIVAL SIGNAL NOT ASSERTED (M / T series)');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('81','FANUC_CNC_FOCAS','OFFSET NUMBER NOT FOUND IN G37 (M / T series)');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('82','FANUC_CNC_FOCAS','H (M series ) / T (T series) -CODE NOT ALLOWED IN G37');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('83','FANUC_CNC_FOCAS','ILLEGAL AXIS COMMAND IN G37 (M / T series)');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('85','FANUC_CNC_FOCAS','COMMUNICATION ERROR');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('86','FANUC_CNC_FOCAS','DR SIGNAL OFF');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('87','FANUC_CNC_FOCAS','BUFFER OVERFLOW');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('88','FANUC_CNC_FOCAS','LAN FILE TRANS ERROR (CHANNEL-1)');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('89','FANUC_CNC_FOCAS','LAN FILE TRANS ERROR (CHANNEL-2)');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('90','FANUC_CNC_FOCAS','REFERENCE RETURN INCOMPLETE');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('91','FANUC_CNC_FOCAS','REFERENCE RETURN INCOMPLETE');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('92','FANUC_CNC_FOCAS','AXES NOT ON THE REFERENCE POINT');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('94','FANUC_CNC_FOCAS','P TYPE NOT ALLOWED (COORD CHG)');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('95','FANUC_CNC_FOCAS','P TYPE NOT ALLOWED (EXT OFS CHG)');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('96','FANUC_CNC_FOCAS','P TYPE NOT ALLOWED (WRK OFS CHG)');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('97','FANUC_CNC_FOCAS','P TYPE NOT ALLOWED (AUTO EXEC)');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('98','FANUC_CNC_FOCAS','G28 FOUND IN SEQUENCE RETURN');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('99','FANUC_CNC_FOCAS','MDI EXEC NOT ALLOWED AFT. SEARCH');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('100','FANUC_CNC_FOCAS','PARAMETER WRITE ENABLE');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('101','FANUC_CNC_FOCAS','PLEASE CLEAR MEMORY');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('109','FANUC_CNC_FOCAS','FORMAT ERROR IN G08 (M series)');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('110','FANUC_CNC_FOCAS','DATA OVERFLOW');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('111','FANUC_CNC_FOCAS','CALCULATED DATA OVERFLOW');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('112','FANUC_CNC_FOCAS','DIVIDED BY ZERO');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('113','FANUC_CNC_FOCAS','IMPROPER COMMAND');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('114','FANUC_CNC_FOCAS','FORMAT ERROR IN MACRO');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('115','FANUC_CNC_FOCAS','ILLEGAL VARIABLE NUMBER');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('116','FANUC_CNC_FOCAS','WRITE PROTECTED VARIABLE');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('118','FANUC_CNC_FOCAS','PARENTHESIS NESTING ERROR');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('119','FANUC_CNC_FOCAS','ILLEGAL ARGUMENT');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('122','FANUC_CNC_FOCAS','FOUR FOLD MACRO MODAL-CALL');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('123','FANUC_CNC_FOCAS','CAN NOT USE MACRO COMMAND IN DNC');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('124','FANUC_CNC_FOCAS','MISSING END STATEMENT');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('125','FANUC_CNC_FOCAS','FORMAT ERROR IN MACRO');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('126','FANUC_CNC_FOCAS','ILLEGAL LOOP NUMBER');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('127','FANUC_CNC_FOCAS','NC, MACRO STATEMENT IN SAME BLOCK');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('128','FANUC_CNC_FOCAS','ILLEGAL MACRO SEQUENCE NUMBER');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('129','FANUC_CNC_FOCAS','ILLEGAL ARGUMENT ADDRESS');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('130','FANUC_CNC_FOCAS','ILLEGAL AXIS OPERATION');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('131','FANUC_CNC_FOCAS','TOO MANY EXTERNAL ALARM MESSAGES');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('132','FANUC_CNC_FOCAS','ALARM NUMBER NOT FOUND');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('133','FANUC_CNC_FOCAS','ILLEGAL DATA IN EXT. ALARM MSG');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('135','FANUC_CNC_FOCAS','ILLEGAL ANGLE  COMMAND (M series) /  SPINDLE ORIENTATION PLEASE (T series)');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('136','FANUC_CNC_FOCAS','C/H-CODE &amp; MOVE CMD IN SAME BLK. (T series)');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('137','FANUC_CNC_FOCAS','M-CODE &amp; MOVE CMD IN SAME BLK.');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('138','FANUC_CNC_FOCAS','SUPERIMPOSED DATA OVERFLOW');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('139','FANUC_CNC_FOCAS','CAN NOT CHANGE PMC CONTROL AXIS');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('141','FANUC_CNC_FOCAS','CAN NOT COMMAND G51 IN CRC (M series)');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('142','FANUC_CNC_FOCAS','ILLEGAL SCALE RATE (M series)');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('143','FANUC_CNC_FOCAS','SCALED MOTION DATA OVERFLOW (M series)');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('144','FANUC_CNC_FOCAS','ILLEGAL PLANE SELECTED (M series)');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('145','FANUC_CNC_FOCAS','ILLEGAL CONDITIONS IN POLAR COORDINATE INTERPOLATION');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('146','FANUC_CNC_FOCAS','IMPROPER G CODE');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('148','FANUC_CNC_FOCAS','ILLEGAL SETTING DATA (M series)');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('149','FANUC_CNC_FOCAS','FORMAT ERROR IN G10L3 (M series)');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('150','FANUC_CNC_FOCAS','ILLEGAL TOOL GROUP NUMBER');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('151','FANUC_CNC_FOCAS','TOOL GROUP NUMBER NOT FOUND');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('152','FANUC_CNC_FOCAS','NO SPACE FOR TOOL ENTRY');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('153','FANUC_CNC_FOCAS','T-CODE NOT FOUND');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('154','FANUC_CNC_FOCAS','NOT USING TOOL IN LIFE GROUP (M series)');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('155','FANUC_CNC_FOCAS','ILLEGAL T-CODE IN M06 (M / T series)');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('156','FANUC_CNC_FOCAS','P/L COMMAND NOT FOUND');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('157','FANUC_CNC_FOCAS','TOO MANY TOOL GROUPS');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('158','FANUC_CNC_FOCAS','ILLEGAL TOOL LIFE DATA');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('159','FANUC_CNC_FOCAS','TOOL DATA SETTING INCOMPLETE');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('163','FANUC_CNC_FOCAS','COMMAND G68/G69 INDEPENDENTLY T series (At two-path)');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('175','FANUC_CNC_FOCAS','ILLEGAL G107 COMMAND');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('176','FANUC_CNC_FOCAS','IMPROPER G-CODE IN G107 (M series) /  G107 (T series)');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('177','FANUC_CNC_FOCAS','CHECK SUM ERROR (G05 MODE)');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('178','FANUC_CNC_FOCAS','G05 COMMANDED IN G41/G42 MODE');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('179','FANUC_CNC_FOCAS','PARAM. (NO. 7510) SETTING ERROR');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('180','FANUC_CNC_FOCAS','COMMUNICATION ERROR (REMOTE BUF)');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('181','FANUC_CNC_FOCAS','FORMAT ERROR IN G81 BLOCK (Hobbing machine, EGB) (M series)');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('182','FANUC_CNC_FOCAS','G81 NOT COMMANDED (Hobbing machine) (M series)');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('183','FANUC_CNC_FOCAS','DUPLICATE G83 (COMMANDS) (Hobbing machine) (M series)');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('184','FANUC_CNC_FOCAS','ILLEGAL COMMAND IN G81 (Hobbing machine, EGB) (M series)');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('185','FANUC_CNC_FOCAS','RETURN TO REFERENCE POINT (Hobbing machine) (M series)');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('186','FANUC_CNC_FOCAS','PARAMETER SETTING ERROR (Hobbing machine, EGB) (M series)');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('187','FANUC_CNC_FOCAS','HOB COMMAND IS NOT ALLOWED');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('190','FANUC_CNC_FOCAS','ILLEGAL AXIS SELECT (M series)');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('194','FANUC_CNC_FOCAS','SPINDLE COMMAND IN SYNCHRO-MODE');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('195','FANUC_CNC_FOCAS','MODE CHANGE ERROR');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('197','FANUC_CNC_FOCAS','C-AXIS COMMANDED IN SPINDLE MODE');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('199','FANUC_CNC_FOCAS','MACRO WORD UNDEFINED');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('200','FANUC_CNC_FOCAS','ILLEGAL S CODE COMMAND');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('201','FANUC_CNC_FOCAS','FEEDRATE NOT FOUND IN RIGID TAP');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('202','FANUC_CNC_FOCAS','POSITION LSI OVERFLOW');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('203','FANUC_CNC_FOCAS','PROGRAM MISS AT RIGID TAPPING');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('204','FANUC_CNC_FOCAS','ILLEGAL AXIS OPERATION');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('205','FANUC_CNC_FOCAS','RIGID MODE DI SIGNAL OFF');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('206','FANUC_CNC_FOCAS','CAN NOT CHANGE PLANE (RIGID TAP) (M series)');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('207','FANUC_CNC_FOCAS','RIGID DATA MISMATCH');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('210','FANUC_CNC_FOCAS','CAN NOT COMAND M198/M199');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('211','FANUC_CNC_FOCAS','G31 (HIGH) NOT ALLOWED IN G99');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('212','FANUC_CNC_FOCAS','ILLEGAL PLANE SELECT (M / T series)');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('213','FANUC_CNC_FOCAS','ILLEGAL COMMAND IN SYNCHRO-MODE  (M / T  series)');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('214','FANUC_CNC_FOCAS','ILLEGAL COMMAND IN SYNCHRO-MODE');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('217','FANUC_CNC_FOCAS','DUPLICATE G51.2 (COMMANDS) (T series)');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('218','FANUC_CNC_FOCAS','NOT FOUND P/Q COMMAND IN G251 (T series)');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('219','FANUC_CNC_FOCAS','COMMAND G250/G251 INDEPENDENTLY (T series)');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('220','FANUC_CNC_FOCAS','ILLEGAL COMMAND IN SYNCHR-MODE (T series)');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('221','FANUC_CNC_FOCAS','ILLEGAL COMMAND IN SYNCHR-MODE (T series)');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('222','FANUC_CNC_FOCAS','DNC OP. NOT ALLOWED IN BG.-EDIT (M series)');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('224','FANUC_CNC_FOCAS','RETURN TO REFERENCE POINT (M / T  series)');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('225','FANUC_CNC_FOCAS','SYNCHRONOUS/MIXED CONTROL ERROR (T series (At two-path))');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('226','FANUC_CNC_FOCAS','ILLEGAL COMMAND IN SYNCHRO- MODE (T series (At two-path))');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('229','FANUC_CNC_FOCAS','CAN NOT KEEP SYNCHRO-STATE (T series)');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('230','FANUC_CNC_FOCAS','R CODE NOT FOUND (Grinding machine) (M series)');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('231','FANUC_CNC_FOCAS','ILLEGAL FORMAT IN G10 OR L50');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('233','FANUC_CNC_FOCAS','DEVICE BUSY');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('239','FANUC_CNC_FOCAS','BP/S ALARM');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('240','FANUC_CNC_FOCAS','BP/S ALARM');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('244','FANUC_CNC_FOCAS','P/S ALARM (T series)');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('245','FANUC_CNC_FOCAS','T-CODE NOT ALOWEE IN THIS BLOCK (T series)');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('251','FANUC_CNC_FOCAS','ATC ERROR (M series)');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('252','FANUC_CNC_FOCAS','ATC SPINDLE ALARM (M series)');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('253','FANUC_CNC_FOCAS','G05 IS NOT AVAILABLE (M series)');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('4500','FANUC_CNC_FOCAS','REPOSITIONING INHIBITED');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('4502','FANUC_CNC_FOCAS','ILLEGAL COMMAND IN BOLT HOLE');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('4503','FANUC_CNC_FOCAS','ILLEGAL COMMAND IN LINE AT ANGLE');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('4504','FANUC_CNC_FOCAS','ILLEGAL COMMAND IN ARC');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('4505','FANUC_CNC_FOCAS','ILLEGAL COMMAND IN GRID');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('4506','FANUC_CNC_FOCAS','ILLEGAL COMMAND IN SHARE PROOFS');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('4507','FANUC_CNC_FOCAS','ILLEGAL COMMAND IN SQUARE');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('4508','FANUC_CNC_FOCAS','ILLEGAL COMMAND IN RADIUS');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('4509','FANUC_CNC_FOCAS','ILLEGAL COMMAND IN CUT AT ANGLE');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('4510','FANUC_CNC_FOCAS','ILLEGAL COMMAND IN LINE-PUNCH');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('4511','FANUC_CNC_FOCAS','ILLEGAL COMMAND IN CIRCLE-PUNCH');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('4520','FANUC_CNC_FOCAS','T, M INHIBITED IN NIBBLING-MODE');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('4521','FANUC_CNC_FOCAS','EXCESS NIBBLING MOVEMENT (X, Y)');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('4522','FANUC_CNC_FOCAS','EXCESS NIBBLING MOVEMENT (C)');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('4523','FANUC_CNC_FOCAS','ILLEGAL COMMAND IN CIRCLE-NIBBL');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('4524','FANUC_CNC_FOCAS','ILLEGAL COMMAND IN LINE-NIBBL');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('4530','FANUC_CNC_FOCAS','A/B MACRO NUMBER ERROR');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('4531','FANUC_CNC_FOCAS','U/V MACRO FORMAT ERROR');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('4532','FANUC_CNC_FOCAS','IMPROPER U/V MACRO NUMBER');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('4533','FANUC_CNC_FOCAS','U/V MACRO MEMORY OVERFLOW');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('4534','FANUC_CNC_FOCAS','W MACRO NUMBER NOT FOUND');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('4535','FANUC_CNC_FOCAS','U/V MACRO NESTING ERROR');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('4536','FANUC_CNC_FOCAS','NO W, Q COMMAND IN MULTI-PIECE');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('4537','FANUC_CNC_FOCAS','ILLEGAL Q VALUE IN MULTI-PIECE');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('4538','FANUC_CNC_FOCAS','W NO. NOT FOUND IN MULTI-PIECE');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('4539','FANUC_CNC_FOCAS','MULTI-PIECE SETTING IS ZERO');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('4540','FANUC_CNC_FOCAS','MULTI-PIECE COMMAND WITHIN MACRO');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('4542','FANUC_CNC_FOCAS','MULTI-PIECE COMMAND ERROR');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('4543','FANUC_CNC_FOCAS','MULTI-PIECE Q COMMAND ERROR');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('4544','FANUC_CNC_FOCAS','MULTI-PIECE RESTART ERROR');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('4549','FANUC_CNC_FOCAS','ILLEGAL TOOL DATA FORMAT');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('4600','FANUC_CNC_FOCAS','T, C COMMAND IN INTERPOLATION');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('4601','FANUC_CNC_FOCAS','INHIBITED T, M COMMAND');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('4602','FANUC_CNC_FOCAS','ILLEGAL T-CODE');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('4603','FANUC_CNC_FOCAS','C AXIS SYNCHRONOUS ERROR');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('4604','FANUC_CNC_FOCAS','ILLEGAL AXIS OPERATION');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('4605','FANUC_CNC_FOCAS','NEED ZRN');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('4630','FANUC_CNC_FOCAS','ILLEGAL COMMAND IN LASER MODE');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('4650','FANUC_CNC_FOCAS','IMPROPER G-CODE IN OFFSET MODE');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('4700','FANUC_CNC_FOCAS','PROGRAM ERROR (OT +)');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('4701','FANUC_CNC_FOCAS','PROGRAM ERROR (OT -)');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('4702','FANUC_CNC_FOCAS','PROGRAM ERROR (OT +)');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('4703','FANUC_CNC_FOCAS','PROGRAM ERROR (OT -)');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('4704','FANUC_CNC_FOCAS','PROGRAM ERROR (OT +)');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('4705','FANUC_CNC_FOCAS','PROGRAM ERROR (OT -)');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('5000','FANUC_CNC_FOCAS','ILLEGAL COMMAND CODE (M series)');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('5003','FANUC_CNC_FOCAS','ILLEGAL PARAMETER (HPCC) (M series)');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('5004','FANUC_CNC_FOCAS','HPCC NOT READY');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('5006','FANUC_CNC_FOCAS','TOO MANY WORD IN ONE BLOCK (M series)');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('5007','FANUC_CNC_FOCAS','TOO LARGE DISTANCE (M series)');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('5009','FANUC_CNC_FOCAS','PARAMETER ZERO (DRY RUN) (M series)');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('5010','FANUC_CNC_FOCAS','END OF RECORD');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('5012','FANUC_CNC_FOCAS','G05 P10000 ILLEGAL START UP (HPCC) (M series)');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('5013','FANUC_CNC_FOCAS','HPCC: CRC OFS REMAIN AT CANCEL (M series)');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('5014','FANUC_CNC_FOCAS','TRACE DATA NOT FOUND (M series)');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('5018','FANUC_CNC_FOCAS','POLYGON SPINDLE SPEED ERROR (T series)');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('5020','FANUC_CNC_FOCAS','PARAMETER OF RESTART ERROR');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('5030','FANUC_CNC_FOCAS','ILLEGAL COMMAND (G100) (T series)');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('5031','FANUC_CNC_FOCAS','ILLEGAL COMMAND (G100, G102, G103) (T series)');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('5032','FANUC_CNC_FOCAS','NEW PRG REGISTERED IN B-AXS MOVE (T series)');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('5033','FANUC_CNC_FOCAS','NO PROG SPACE IN MEMORY B-AXS (T series)');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('5034','FANUC_CNC_FOCAS','PLURAL COMMAND IN G110 (T series)');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('5035','FANUC_CNC_FOCAS','NO FEEDRATE COMMANDED B-AXS (T series)');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('5036','FANUC_CNC_FOCAS','ADDRESS R NOT DEFINED IN G81-G86 (T series)');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('5037','FANUC_CNC_FOCAS','ADDRESS Q NOT DEFINED IN G83 (T series)');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('5038','FANUC_CNC_FOCAS','TOO MANY START M-CODE COMMAND (T series)');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('5039','FANUC_CNC_FOCAS','START UNREGISTERED B-AXS PROG (T series)');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('5040','FANUC_CNC_FOCAS','CAN NOT COMMANDED B-AXS MOVE (T series)');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('5041','FANUC_CNC_FOCAS','CAN NOT COMMANDED G110 BLOCK (T series)');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('5044','FANUC_CNC_FOCAS','G68 FORMAT ERROR (M series)');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('5046','FANUC_CNC_FOCAS','ILLEGAL PARAMETER (ST.COMP)');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('5050','FANUC_CNC_FOCAS','ILL-COMMAND IN CHOPPING MODE (M series)');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('5051','FANUC_CNC_FOCAS','M-NET CODE ERROR');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('5052','FANUC_CNC_FOCAS','M-NET ETX ERROR');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('5053','FANUC_CNC_FOCAS','M-NET CONNECT ERROR');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('5054','FANUC_CNC_FOCAS','M-NET RECEIVE ERROR');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('5055','FANUC_CNC_FOCAS','M-NET PRT/FRT ERROR');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('5057','FANUC_CNC_FOCAS','M-NET BOARD SYSTEM DOWN');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('5058','FANUC_CNC_FOCAS','G35/G36 FORMAT ERROR (T series)');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('5059','FANUC_CNC_FOCAS','RADIUS IS OUT OF RANGE  (M / T  series)');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('5060','FANUC_CNC_FOCAS','ILLEGAL PARAMETER IN G02.3/G03.3 (M series)');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('5061','FANUC_CNC_FOCAS','ILLEGAL FORMAT IN G02.3/G03.3 (M series)');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('5062','FANUC_CNC_FOCAS','ILLEGAL COMMAND IN G02.3/G03.3');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('5063','FANUC_CNC_FOCAS','IS NOT PRESET AFTER REF. (M series)');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('5064','FANUC_CNC_FOCAS','DIFFERRENT AXIS UNIT (IS-B, IS-C)');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('5065','FANUC_CNC_FOCAS','DIFFERENT AXIS UNIT (PMC AXIS) (M series)');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('5067','FANUC_CNC_FOCAS','(HPCC) (M series)');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('5068','FANUC_CNC_FOCAS','G31 FORMAT ERROR (M series)');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('5069','FANUC_CNC_FOCAS','WHL-C:ILLEGA P-DATA (M series)');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('5073','FANUC_CNC_FOCAS','NO DECIMAL POINT');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('5074','FANUC_CNC_FOCAS','ADDRESS DUPLICATION ERROR');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('5082','FANUC_CNC_FOCAS','DATA SERVER ERROR');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('5085','FANUC_CNC_FOCAS','SMOOTH IPL ERROR 1');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('5096','FANUC_CNC_FOCAS','MISMATCH WAITING M-CODE');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('5110','FANUC_CNC_FOCAS','IMPROPER G-CODE (G05.1 G1 MODE) (M series)');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('5111','FANUC_CNC_FOCAS','IMPROPER MODAL G-CODE (G05.1 G1) (M series)');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('5112','FANUC_CNC_FOCAS','G08 CAN NOT BE COMMANDED (G05.1 G1) (M series)');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('5113','FANUC_CNC_FOCAS','CAN NOT ERROR IN MDI MODE (G05.1) (M series)');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('5114','FANUC_CNC_FOCAS','NOT STOP POSITION (G05.1 Q1) (M series)');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('5115','FANUC_CNC_FOCAS','SPL : ERROR (M series)');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('5116','FANUC_CNC_FOCAS','SPL : ERROR (M series)');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('5117','FANUC_CNC_FOCAS','SPL : ERROR (M series)');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('5118','FANUC_CNC_FOCAS','SPL : ERROR (M series)');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('5122','FANUC_CNC_FOCAS','ILLEGAL COMMAND IN SPIRAL (M series)');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('5123','FANUC_CNC_FOCAS','OVER TOLERANCE OF END POINT (M series)');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('5124','FANUC_CNC_FOCAS','CAN NOT COMMAND SPIRAL (M series)');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('5134','FANUC_CNC_FOCAS','FSSB : OPEN READY TIME OUT');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('5135','FANUC_CNC_FOCAS','FSSB : ERROR MODE');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('5136','FANUC_CNC_FOCAS','FSSB : NUMBER OF AMPS IS SMALL');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('5137','FANUC_CNC_FOCAS','FSSB : CONFIGURATION ERROR');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('5138','FANUC_CNC_FOCAS','FSSB : AXIS SETTING NOT COMPLETE');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('5139','FANUC_CNC_FOCAS','FSSB : ERROR');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('5155','FANUC_CNC_FOCAS','NOT RESTART PROGRAM BY G05');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('5156','FANUC_CNC_FOCAS','ILLEGAL AXIS OPERATION (M series)');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('5157','FANUC_CNC_FOCAS','PARAMETER ZERO (M series)');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('5195','FANUC_CNC_FOCAS','DIRECTION CAN NOT BE JUDGED (T series)');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('5196','FANUC_CNC_FOCAS','ILLEGAL OPERATION (HPCC) (M series)');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('5197','FANUC_CNC_FOCAS','FSSB : OPEN TIME OUT');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('5198','FANUC_CNC_FOCAS','FSSB : ID DATA NOT READ');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('5199','FANUC_CNC_FOCAS','FINE TORQUE SENSING PARAMETER');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('5212','FANUC_CNC_FOCAS','SCREEN COPY : PARAMETER ERROR');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('5213','FANUC_CNC_FOCAS','SCREEN COPY : COMMUNICATION ERROR');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('5214','FANUC_CNC_FOCAS','SCREEN COPY : DATA TRANSFER ERROR');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('5218','FANUC_CNC_FOCAS','ILLEGAL PARAMETER (INCL. COMP)');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('5219','FANUC_CNC_FOCAS','CAN NOT RETURN');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('5220','FANUC_CNC_FOCAS','REFERENCE POINT ADJUSTMENT MODE');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('5222','FANUC_CNC_FOCAS','SRAM CORRECTABLE ERROR');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('5227','FANUC_CNC_FOCAS','FILE NOT FOUND');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('5228','FANUC_CNC_FOCAS','SAME NAME USED');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('5229','FANUC_CNC_FOCAS','WRITE PROTECTED');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('5231','FANUC_CNC_FOCAS','TOO MANY FILES');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('5232','FANUC_CNC_FOCAS','DATA OVER-FLOW');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('5235','FANUC_CNC_FOCAS','COMMUNICATION ERROR');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('5237','FANUC_CNC_FOCAS','READ ERROR');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('5238','FANUC_CNC_FOCAS','WRITE ERROR');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('5242','FANUC_CNC_FOCAS','ILLEGAL AXIS NUMBER (M series)');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('5243','FANUC_CNC_FOCAS','DATA OUT OF RANGE (M series)');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('5244','FANUC_CNC_FOCAS','TOO MANY DI ON (M series)');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('5245','FANUC_CNC_FOCAS','OTHER AXIS ARE COMMANDED (M series)');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('5251','FANUC_CNC_FOCAS','ILLEGAL PARAMETER IN G54.2 (M series)');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('5252','FANUC_CNC_FOCAS','ILLEGAL P COMMAND IN G54.2 (M series)');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('5257','FANUC_CNC_FOCAS','G41/G42 NOT ALLOWED IN MDI MODE (M / T series)');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('5300','FANUC_CNC_FOCAS','SET ALL OFFSET DATAS AGAIN');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('5302','FANUC_CNC_FOCAS','ILLEGAL COMMAND IN G68 MODE');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('5303','FANUC_CNC_FOCAS','TOUCH PANEL ERROR');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('5306','FANUC_CNC_FOCAS','MODE CHANGE ERROR');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('5307','FANUC_CNC_FOCAS','INTERNAL DATA OVER FLOW (M series)');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('5311','FANUC_CNC_FOCAS','FSSB:ILLEGAL CONNECTION');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('5321','FANUC_CNC_FOCAS','S-COMP. VALUE OVERFLOW');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('5400','FANUC_CNC_FOCAS','SPL:ILLEGAL AXIS COMMAND (M series)');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('5401','FANUC_CNC_FOCAS','SPL:ILLEGAL COMMAND (M series)');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('5402','FANUC_CNC_FOCAS','SPL:ILLEGAL AXIS MOVING (M series)');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('5403','FANUC_CNC_FOCAS','SPL:CAN NOT MAKE VECTOR (M series)');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('5405','FANUC_CNC_FOCAS','ILLEGAL PARAMETER IN G41.2/ G42.2 (M series)');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('5406','FANUC_CNC_FOCAS','G41.3/G40 FORMAT ERROR (M series)');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('5407','FANUC_CNC_FOCAS','ILLEGAL COMMAND IN G41.3 (M series)');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('5408','FANUC_CNC_FOCAS','G41.3 ILLEGAL START_UP (M series)');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('5409','FANUC_CNC_FOCAS','ILLEGAL PARAMETER IN G41.3 (M series)');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('5411','FANUC_CNC_FOCAS','NURBS:ILLEGAL ORDER (M series)');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('5412','FANUC_CNC_FOCAS','NURBS:NO KNOT COMMAND (M series)');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('5413','FANUC_CNC_FOCAS','NURBS:ILLEGAL AXIS COMMAND (M series)');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('5414','FANUC_CNC_FOCAS','NURBS:ILLEGAL KNOT (M series)');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('5415','FANUC_CNC_FOCAS','NURBS:ILLEGAL CANCEL (M series)');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('5416','FANUC_CNC_FOCAS','NURBS:ILLEGAL MODE (M series)');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('5417','FANUC_CNC_FOCAS','NURBS:ILLEGAL MULTI-KNOT (M series)');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('5418','FANUC_CNC_FOCAS','NURBS:ILLEGAL KNOT VALUE (M series)');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('5420','FANUC_CNC_FOCAS','ILLEGAL PARAMETER IN G43.4/ G43.5 (M series)');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('5421','FANUC_CNC_FOCAS','ILLEGAL COMMAND IN G43.4/ G43.5 (M series)');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('5422','FANUC_CNC_FOCAS','EXCESS VELOCITY IN G43.4/ G43.5 (M series)');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('5425','FANUC_CNC_FOCAS','ILLEGAL OFFSET VALUE (M series)');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('5430','FANUC_CNC_FOCAS','ILLEGAL COMMAND IN 3-D CIR (M series)');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('5432','FANUC_CNC_FOCAS','G02.4/G03.4 FORMAT ERROR (M series)');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('5433','FANUC_CNC_FOCAS','MANUAL INTERVENTION IN 3-D CIR (M series)');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('5435','FANUC_CNC_FOCAS','PARAMETER OUT OF RANGE (TLAC) (M series)');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('5436','FANUC_CNC_FOCAS','PARAMETER SETTING ERROR 1 (TLAC) (M series)');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('5437','FANUC_CNC_FOCAS','PARAMETER SETTING ERROR 2 (TLAC) (M series)');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('5440','FANUC_CNC_FOCAS','ILLEGAL DRILLING AXIS SELECTED (M series)');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('5445','FANUC_CNC_FOCAS','CRC:MOTION IN G39 (M series)');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('5446','FANUC_CNC_FOCAS','CRC:NO AVOIDANCE (M series)');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('5447','FANUC_CNC_FOCAS','CRC:DANGEROUS AVOIDANCE (M series)');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('5448','FANUC_CNC_FOCAS','CRC:INTERFERENCE TO AVD. (M series)');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('5452','FANUC_CNC_FOCAS','IMPROPER G-CODE (5AXIS MODE) (M series)');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('5453','FANUC_CNC_FOCAS','NOTE: G68 IS CANCELED (HPCC) (M series)');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('5455','FANUC_CNC_FOCAS','ILLEGAL ACC. PARAMETER (M series)');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('400','FANUC_CNC_FOCAS','SERVO ALARM: n-TH AXIS OVERLOAD');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('401','FANUC_CNC_FOCAS','SERVO ALARM: n-TH AXIS VRDY OFF');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('402','FANUC_CNC_FOCAS','SERVO ALARM: SV CARD NOT EXIST');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('403','FANUC_CNC_FOCAS','SERVO ALARM: CARD/SOFT MISMATCH');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('404','FANUC_CNC_FOCAS','SERVO ALARM: n-TH AXIS VRDY ON');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('405','FANUC_CNC_FOCAS','SERVO ALARM: (ZERO POINT RETURN FAULT)');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('407','FANUC_CNC_FOCAS','SERVO ALARM: EXCESS ERROR');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('409','FANUC_CNC_FOCAS','SERVO ALARM: n AXIS TORQUE ALM');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('410','FANUC_CNC_FOCAS','SERVO ALARM: n-TH AXIS - EXCESS ERROR');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('411','FANUC_CNC_FOCAS','SERVO ALARM: n-TH AXIS - EXCESS ERROR');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('413','FANUC_CNC_FOCAS','SERVO ALARM: n-th AXIS - LSI OVERFLOW');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('414','FANUC_CNC_FOCAS','SERVO ALARM: n-TH AXIS - DETECTION RELATED ERROR');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('415','FANUC_CNC_FOCAS','SERVO ALARM: n-TH AXIS - EXCESS SHIFT');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('416','FANUC_CNC_FOCAS','SERVO ALARM: n-TH AXIS - DISCONNECTION');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('417','FANUC_CNC_FOCAS','SERVO ALARM: n-TH AXIS - PARAMETER INCORRECT');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('420','FANUC_CNC_FOCAS','SERVO ALARM: n AXIS SYNC TORQUE (M series)');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('421','FANUC_CNC_FOCAS','SERVO ALARM: n AXIS EXCESS ER (D)');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('422','FANUC_CNC_FOCAS','SERVO ALARM: n AXIS');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('423','FANUC_CNC_FOCAS','SERVO ALARM: n AXIS');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('430','FANUC_CNC_FOCAS','n AXIS : SV. MOTOR OVERHEAT');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('431','FANUC_CNC_FOCAS','n AXIS : CNV. OVERLOAD');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('432','FANUC_CNC_FOCAS','n AXIS : CNV. LOW VOLT CONTROL');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('433','FANUC_CNC_FOCAS','n AXIS : CNV. LOW VOLT DC LINK');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('434','FANUC_CNC_FOCAS','n AXIS : INV. LOW VOLT CONTROL');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('435','FANUC_CNC_FOCAS','n AXIS : INV. LOW VOLT DC LINK');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('436','FANUC_CNC_FOCAS','n AXIS : SOFTTHERMAL (OVC)');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('437','FANUC_CNC_FOCAS','n AXIS : CNV. OVERCURRENT POWER');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('438','FANUC_CNC_FOCAS','n AXIS : INV. ABNORMAL CURRENT');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('439','FANUC_CNC_FOCAS','n AXIS : CNV. OVER VOLT DC LINK');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('440','FANUC_CNC_FOCAS','n AXIS : CNV. EX DECELERATION POW.');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('441','FANUC_CNC_FOCAS','n AXIS : ABNORMAL CURRENT OFFSET');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('442','FANUC_CNC_FOCAS','n AXIS : CNV. CHARGE FAILURE');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('443','FANUC_CNC_FOCAS','n AXIS : CNV. COOLING FAN FAILURE');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('444','FANUC_CNC_FOCAS','n AXIS : INV. COOLING FAN FAILURE');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('445','FANUC_CNC_FOCAS','n AXIS : SOFT DISCONNECT ALARM');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('446','FANUC_CNC_FOCAS','n AXIS : HARD DISCONNECT ALARM');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('447','FANUC_CNC_FOCAS','n AXIS : HARD DISCONNECT (EXT)');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('448','FANUC_CNC_FOCAS','n AXIS : UNMATCHED FEEDBACK ALARM');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('449','FANUC_CNC_FOCAS','n AXIS : INV. IPM ALARM');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('453','FANUC_CNC_FOCAS','n AXIS : SPC SOFT DISCONNECT ALARM');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('456','FANUC_CNC_FOCAS','n AXIS : ILLEGAL CURRENT LOOP');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('457','FANUC_CNC_FOCAS','n AXIS : ILLEGAL HI HRV (250US)');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('458','FANUC_CNC_FOCAS','n AXIS : CURRENT LOOP ERROR');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('459','FANUC_CNC_FOCAS','n AXIS : HI HRV SETTING ERROR');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('460','FANUC_CNC_FOCAS','n AXIS : FSSB DISCONNECT');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('461','FANUC_CNC_FOCAS','n AXIS : ILLEGAL AMP INTERFACE');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('462','FANUC_CNC_FOCAS','n AXIS : SEND CNC DATA FAILED');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('463','FANUC_CNC_FOCAS','n AXIS : SEND SLAVE DATA FAILED');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('464','FANUC_CNC_FOCAS','n AXIS : WRITE ID DATA FAILED');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('465','FANUC_CNC_FOCAS','n AXIS : READ ID DATA FAILED');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('466','FANUC_CNC_FOCAS','n AXIS : MOTOR/AMP COMBINATION');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('467','FANUC_CNC_FOCAS','n AXIS : ILLEGAL SETTING OF AXIS');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('468','FANUC_CNC_FOCAS','n AXIS : HI HRV SETTING ERROR (AMP)');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('300','FANUC_CNC_FOCAS','n AXIS NEED ZRN');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('301','FANUC_CNC_FOCAS','APC ALARM:n AXIS COMMUNICATION');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('302','FANUC_CNC_FOCAS','APC ALARM:n AXIS OVER TIME');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('303','FANUC_CNC_FOCAS','APC ALARM:n AXIS FRAMING');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('304','FANUC_CNC_FOCAS','APC ALARM:n AXIS PARITY');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('305','FANUC_CNC_FOCAS','APC ALARM:n AXIS PULSE MISS');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('306','FANUC_CNC_FOCAS','APC ALARM:n AXIS BATTERY ZERO');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('307','FANUC_CNC_FOCAS','APC ALARM:n AXIS BATTERY DOWN 1');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('308','FANUC_CNC_FOCAS','APC ALARM:n AXIS BATTERY DOWN 2');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('309','FANUC_CNC_FOCAS','APC ALARM:n AXIS ZRN IMPOSSIBLE');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('360','FANUC_CNC_FOCAS','n AXIS : ABNORMAL CHECKSUM (INT)');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('361','FANUC_CNC_FOCAS','n AXIS : ABNORMAL PHASE DATA (INT)');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('362','FANUC_CNC_FOCAS','n AXIS : ABNORMAL REV.DATA (INT)');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('363','FANUC_CNC_FOCAS','n AXIS : ABNORMAL CLOCK (INT)');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('364','FANUC_CNC_FOCAS','n AXIS : SOFT PHASE ALARM (INT)');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('365','FANUC_CNC_FOCAS','n AXIS : BROKEN LED (INT)');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('366','FANUC_CNC_FOCAS','n AXIS : PULSE MISS (INT)');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('367','FANUC_CNC_FOCAS','n AXIS : COUNT MISS (INT)');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('368','FANUC_CNC_FOCAS','n AXIS : SERIAL DATA ERROR (INT)');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('369','FANUC_CNC_FOCAS','n AXIS : DATA TRANS. ERROR (INT)');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('380','FANUC_CNC_FOCAS','n AXIS : BROKEN LED (EXT)');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('381','FANUC_CNC_FOCAS','n AXIS : ABNORMAL PHASE (EXT LIN)');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('382','FANUC_CNC_FOCAS','n AXIS : COUNT MISS (EXT)');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('383','FANUC_CNC_FOCAS','n AXIS : PULSE MISS (EXT)');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('384','FANUC_CNC_FOCAS','n AXIS : SOFT PHASE ALARM (EXT)');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('385','FANUC_CNC_FOCAS','n AXIS : SERIAL DATA ERROR (EXT)');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('386','FANUC_CNC_FOCAS','n AXIS : DATA TRANS. ERROR (EXT)');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('387','FANUC_CNC_FOCAS','n AXIS : ABNORMAL ENCODER (EXT)');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('500','FANUC_CNC_FOCAS','OVER TRAVEL : +n');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('501','FANUC_CNC_FOCAS','OVER TRAVEL : -n');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('502','FANUC_CNC_FOCAS','OVER TRAVEL : +n');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('503','FANUC_CNC_FOCAS','OVER TRAVEL : -n');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('504','FANUC_CNC_FOCAS','OVER TRAVEL : +n');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('505','FANUC_CNC_FOCAS','OVER TRAVEL : -n');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('506','FANUC_CNC_FOCAS','OVER TRAVEL : +n');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('507','FANUC_CNC_FOCAS','OVER TRAVEL : -n');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('700','FANUC_CNC_FOCAS','OVERHEAT: CONTROL UNIT');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('701','FANUC_CNC_FOCAS','OVERHEAT: FAN MOTOR');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('704','FANUC_CNC_FOCAS','OVERHEAT: SPINDLE');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('740','FANUC_CNC_FOCAS','RIGID TAP ALARM : EXCESS ERROR');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('741','FANUC_CNC_FOCAS','RIGID TAP ALARM : EXCESS ERROR');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('742','FANUC_CNC_FOCAS','RIGID TAP ALARM : LSI OVER FLOW');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('749','FANUC_CNC_FOCAS','S-SPINDLE LSI ERROR');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('750','FANUC_CNC_FOCAS','SPINDLE SERIAL LINK START FAULT');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('751','FANUC_CNC_FOCAS','FIRST SPINDLE ALARM DETECTION (AL-XX)');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('752','FANUC_CNC_FOCAS','FIRST SPINDLE MODE CHANGE FAULT');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('754','FANUC_CNC_FOCAS','SPINDLE-1 ABNORMAL TORQUE ALM');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('761','FANUC_CNC_FOCAS','SECOND SPINDLE ALARM DETECTION (AL-XX)');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('762','FANUC_CNC_FOCAS','SECOND SPINDLE MODE CHANGE FAULT');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('764','FANUC_CNC_FOCAS','SPINDLE-2 ABNORMAL TORQUE ALM');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('771','FANUC_CNC_FOCAS','SPINDLE-3 ALARM DETECT (AL-XX)');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('772','FANUC_CNC_FOCAS','SPINDLE-3 MODE CHANGE ERROR');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('774','FANUC_CNC_FOCAS','SPINDLE-3 ABNORMAL TORQUE ALM');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('782','FANUC_CNC_FOCAS','SPINDLE-4 MODE CHANGE ERROR');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('784','FANUC_CNC_FOCAS','SPINDLE-4 ABNORMAL TORQUE ALM');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('4800','FANUC_CNC_FOCAS','ZONE : PUNCHING INHIBITED 1');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('4801','FANUC_CNC_FOCAS','ZONE : PUNCHING INHIBITED 2');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('4802','FANUC_CNC_FOCAS','ZONE : PUNCHING INHIBITED 3');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('4803','FANUC_CNC_FOCAS','ZONE : PUNCHING INHIBITED 4');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('4810','FANUC_CNC_FOCAS','ZONE : ENTERING INHIBITED 1 +X');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('4811','FANUC_CNC_FOCAS','ZONE : ENTERING INHIBITED 1 -X');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('4812','FANUC_CNC_FOCAS','ZONE : ENTERING INHIBITED 2 +X');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('4813','FANUC_CNC_FOCAS','ZONE : ENTERING INHIBITED 2 -X');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('4814','FANUC_CNC_FOCAS','ZONE : ENTERING INHIBITED 3 +X');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('4815','FANUC_CNC_FOCAS',' ZONE : ENTERING INHIBITED 3 -X');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('4816','FANUC_CNC_FOCAS','ZONE : ENTERING INHIBITED 4 +X');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('4817','FANUC_CNC_FOCAS','ZONE : ENTERING INHIBITED 4 -X');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('4830','FANUC_CNC_FOCAS','ZONE : ENTERING INHIBITED 1 +Y');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('4831','FANUC_CNC_FOCAS','ZONE : ENTERING INHIBITED 1 -Y');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('4832','FANUC_CNC_FOCAS','ZONE : ENTERING INHIBITED 2 +Y');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('4833','FANUC_CNC_FOCAS','ZONE : ENTERING INHIBITED 2 -Y');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('4834','FANUC_CNC_FOCAS','ZONE : ENTERING INHIBITED 3 +Y');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('4835','FANUC_CNC_FOCAS','ZONE : ENTERING INHIBITED 3 -Y');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('4836','FANUC_CNC_FOCAS','ZONE : ENTERING INHIBITED 4 +Y');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('4837','FANUC_CNC_FOCAS','ZONE : ENTERING INHIBITED 4 -Y');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('4870','FANUC_CNC_FOCAS','AUTO SETTING FEED ERROR');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('4871','FANUC_CNC_FOCAS','AUTO SETTING PIECES ERROR');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('4872','FANUC_CNC_FOCAS','AUTO SETTING COMMAND ERROR');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('900','FANUC_CNC_FOCAS','ROM PARITY');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('910','FANUC_CNC_FOCAS','SRAM PARITY : (BYTE 0)');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('911','FANUC_CNC_FOCAS','SRAM PARITY : (BYTE 1)');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('912','FANUC_CNC_FOCAS','DRAM PARITY : (BYTE 0)');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('913','FANUC_CNC_FOCAS','DRAM PARITY : (BYTE 1)');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('914','FANUC_CNC_FOCAS','DRAM PARITY : (BYTE 2)');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('915','FANUC_CNC_FOCAS','DRAM PARITY : (BYTE 3)');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('916','FANUC_CNC_FOCAS','DRAM PARITY : (BYTE 4)');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('917','FANUC_CNC_FOCAS','DRAM PARITY : (BYTE 5)');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('918','FANUC_CNC_FOCAS','DRAM PARITY : (BYTE 6)');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('919','FANUC_CNC_FOCAS','DRAM PARITY : (BYTE 7)');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('920','FANUC_CNC_FOCAS','SERVO ALARM (1-4 AXIS)');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('921','FANUC_CNC_FOCAS','SERVO ALARM (5-8 AXIS)');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('926','FANUC_CNC_FOCAS','FSSB ALARM');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('930','FANUC_CNC_FOCAS','CPU INTERRUPUT');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('935','FANUC_CNC_FOCAS','SRAM ECC ERROR');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('950','FANUC_CNC_FOCAS','PMC SYSTEM ALARM');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('951','FANUC_CNC_FOCAS','PMC WATCH DOG ALARM');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('970','FANUC_CNC_FOCAS','NMI OCCURRED IN PMCLSI');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('971','FANUC_CNC_FOCAS','NMI OCCURRED IN SLC');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('972','FANUC_CNC_FOCAS','NMI OCCURRED IN OTHER MODULE');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('973','FANUC_CNC_FOCAS','NON MASK INTERRUPT');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('974','FANUC_CNC_FOCAS','F-BUS ERROR');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('975','FANUC_CNC_FOCAS','BUS ERROR');
insert into m_alarm (alarm_id, cnc_id, alarm_status) values ('976','FANUC_CNC_FOCAS','L-BUS ERROR');


