SET FOREIGN_KEY_CHECKS = 0;
TRUNCATE TABLE a_chengshiu_agv;
TRUNCATE TABLE a_chengshiu_agv_rfid;
TRUNCATE TABLE a_chengshiu_alarm;
TRUNCATE TABLE a_chengshiu_alert_log;
TRUNCATE TABLE a_chengshiu_alert_type;
TRUNCATE TABLE a_chengshiu_conversion_factor;
TRUNCATE TABLE a_chengshiu_customer;
TRUNCATE TABLE a_chengshiu_demand2_order;
TRUNCATE TABLE a_chengshiu_demand_order;
TRUNCATE TABLE a_chengshiu_demand_reason;
TRUNCATE TABLE a_chengshiu_line;
TRUNCATE TABLE a_chengshiu_ma_setting;
TRUNCATE TABLE a_chengshiu_ma_setting_agv;
TRUNCATE TABLE a_chengshiu_machine;
TRUNCATE TABLE a_chengshiu_machine_material;
TRUNCATE TABLE a_chengshiu_material;
TRUNCATE TABLE a_chengshiu_material_item;
TRUNCATE TABLE a_chengshiu_order_shipping;
TRUNCATE TABLE a_chengshiu_product;
TRUNCATE TABLE a_chengshiu_sales_order;
TRUNCATE TABLE a_chengshiu_sales_order_details;
TRUNCATE TABLE a_chengshiu_sensor;
TRUNCATE TABLE a_chengshiu_sensor_alarm;
TRUNCATE TABLE a_chengshiu_sensor_type;
TRUNCATE TABLE a_chengshiu_store_product;
TRUNCATE TABLE a_chengshiu_store_sales_record;
TRUNCATE TABLE a_chengshiu_storing;
TRUNCATE TABLE a_chengshiu_storing_area;
TRUNCATE TABLE a_chengshiu_storing_shelf;
TRUNCATE TABLE a_chengshiu_trace;
TRUNCATE TABLE a_chengshiu_trace_machine;
TRUNCATE TABLE a_chengshiu_trace_material;
TRUNCATE TABLE a_chengshiu_trace_work;
TRUNCATE TABLE a_chengshiu_work_order;
TRUNCATE TABLE a_chengshiu_work_order_duration;
DELETE FROM m_sys_user_group WHERE group_id = 'sys_chengshiu_store_group';
DELETE FROM m_sys_user where modify_by = 'admin';
SET FOREIGN_KEY_CHECKS = 1;